-- Seed idempotente dei contenuti pubblici già presenti nel portfolio locale.
insert into public.site_settings (key, value, is_public) values
  ('site.language.default', '"it"'::jsonb, true),
  ('site.theme.default', '"system"'::jsonb, true),
  ('site.public_url', '""'::jsonb, true),
  ('sections.order', '["hero","profile","case-study","skills","technical-lab","evidence","experience","certificates","contact"]'::jsonb, true)
on conflict (key) do nothing;

insert into public.content_items
  (content_type, slug, title_it, title_en, body_it, body_en, data, sort_order, status)
values
  ('hero','hero-name','Gaetano Russo','Gaetano Russo','','', '{"selector":"#hero-title"}'::jsonb,0,'published'),
  ('hero','hero-intro','Introduzione hero','Hero introduction','Gestisco sistemi, utenti e connettività in contesti aziendali con un approccio metodico alla diagnosi; applico lo stesso metodo anche ai progetti web.','I manage systems, users and connectivity in corporate environments with a methodical approach to diagnostics, and apply the same method to web projects.','{"selector":".hero-intro"}'::jsonb,1,'published'),
  ('profile','profile-positioning','Posizionamento profilo','Profile positioning','L’infrastruttura IT è il mio lavoro principale. Il web è il percorso che sto costruendo accanto.','IT infrastructure is my main role. Web development is the path I am building alongside it.','{"selector":".profile-story__heading h2"}'::jsonb,0,'published'),
  ('contact_copy','contact-introduction','Introduzione contatti','Contact introduction','Se vuoi conoscere meglio la mia esperienza, approfondire un progetto o valutare un’opportunità professionale, puoi contattarmi qui.','If you would like to learn more about my experience, discuss a project or explore a professional opportunity, you can contact me here.','{"selector":".contact-copy > p:last-of-type"}'::jsonb,0,'published'),
  ('seo','homepage-description','Meta description homepage','Homepage meta description','Portfolio di Gaetano Russo, IT Infrastructure Specialist: sistemi Windows, Active Directory, networking, SAP e progetti web tecnici.','Gaetano Russo portfolio: IT infrastructure, Windows systems, Active Directory, networking, SAP and technical web projects.','{"selector":"meta[name=description]"}'::jsonb,0,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('section','hero','Hero','Hero','{"selector":"#home","visible":true}'::jsonb,10,'published'),
  ('section','profile','Profilo','Profile','{"selector":"#chi-sono","visible":true}'::jsonb,20,'published'),
  ('section','skills','Competenze','Skills','{"selector":"#competenze","visible":true}'::jsonb,30,'published'),
  ('section','technical-lab','Technical Lab','Technical Lab','{"selector":"#technical-lab","visible":true}'::jsonb,40,'published'),
  ('section','evidence','Evidenze','Evidence','{"selector":"#evidenze","visible":true}'::jsonb,50,'published'),
  ('section','experience','Esperienze','Experience','{"selector":"#esperienze","visible":true}'::jsonb,60,'published'),
  ('section','certificates','Attestati','Certificates','{"selector":"#certificazioni","visible":true}'::jsonb,70,'published'),
  ('section','curriculum','Curriculum','Curriculum','{"selector":"#curriculum","visible":true}'::jsonb,80,'published'),
  ('section','contact','Contatti','Contact','{"selector":"#contatti","visible":true}'::jsonb,90,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('skill','windows-server','Windows Server','Windows Server',$json${"track":"it","name":"Windows Server","detail":{"it":"Amministrazione, manutenzione, file server e servizi di dominio.","en":"Administration, maintenance, file servers and domain services."}}$json$::jsonb,10,'published'),
  ('skill','active-directory','Active Directory','Active Directory',$json${"track":"it","name":"Active Directory","detail":{"it":"Utenti, gruppi, OU, permessi, GPO e autenticazione centralizzata.","en":"Users, groups, OUs, permissions, GPOs and centralised authentication."}}$json$::jsonb,20,'published'),
  ('skill','dns-dhcp','DNS e DHCP','DNS and DHCP',$json${"track":"it","name":"DNS & DHCP","detail":{"it":"Servizi di rete, indirizzamento e diagnosi della connettività.","en":"Network services, addressing and connectivity diagnostics."}}$json$::jsonb,30,'published'),
  ('skill','lan-vlan-vpn','LAN, VLAN e VPN','LAN, VLAN and VPN',$json${"track":"it","name":"LAN · VLAN · VPN","detail":{"it":"Routing, switching, segmentazione e accessi remoti sicuri.","en":"Routing, switching, segmentation and secure remote access."}}$json$::jsonb,40,'published'),
  ('skill','supporto-sap','Supporto SAP','SAP Support',$json${"track":"it","name":{"it":"Supporto SAP","en":"SAP Support"},"detail":{"it":"SAP GUI, SAP Router, utenti, trasporti CR e troubleshooting.","en":"SAP GUI, SAP Router, users, CR transports and troubleshooting."}}$json$::jsonb,50,'published'),
  ('skill','supporto-enterprise','Supporto enterprise','Enterprise support',$json${"track":"it","name":{"it":"Supporto enterprise","en":"Enterprise support"},"detail":{"it":"Gestione utenti, workstation, periferiche e continuità operativa.","en":"User, workstation and device management with operational continuity."}}$json$::jsonb,60,'published'),
  ('skill','html-css','HTML e CSS','HTML and CSS',$json${"track":"web","name":"HTML & CSS","detail":{"it":"Interfacce semantiche, responsive e accessibili.","en":"Semantic, responsive and accessible interfaces."}}$json$::jsonb,70,'published'),
  ('skill','javascript','JavaScript','JavaScript',$json${"track":"web","name":"JavaScript","detail":{"it":"Interazioni, filtri, modali, preferenze e progressive enhancement.","en":"Interactions, filters, dialogs, preferences and progressive enhancement."}}$json$::jsonb,80,'published'),
  ('skill','git-github','Git e GitHub','Git and GitHub',$json${"track":"web","name":"Git & GitHub","detail":{"it":"Versionamento e workflow di rilascio controllato.","en":"Version control and controlled release workflows."}}$json$::jsonb,90,'published'),
  ('skill','responsive-seo','Responsive e SEO','Responsive and SEO',$json${"track":"web","name":"Responsive & SEO","detail":{"it":"Esperienze coerenti su ogni dispositivo e struttura indicizzabile.","en":"Consistent cross-device experiences and indexable structure."}}$json$::jsonb,100,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('experience','zilmet','ZILMET S.P.A.','ZILMET S.P.A.',$json${"period":{"it":"01/2024 — Presente","en":"Jan 2024 — Present"},"company":"ZILMET S.P.A.","focus":{"it":"Responsabilità attuale · infrastruttura e operations","en":"Current role · infrastructure and operations"},"role":{"it":"IT Infrastructure Specialist · System Administrator · SAP Support","en":"IT Infrastructure Specialist · System Administrator · SAP Support"},"detail":{"it":"Gestione infrastruttura IT, VMware, Windows Server, Active Directory, VPN e supporto operativo per ambiente produttivo.","en":"IT infrastructure, VMware, Windows Server, Active Directory, VPN and operational support for a production environment."}}$json$::jsonb,10,'published'),
  ('experience','lets-co','LET’S CO S.R.L.','LET’S CO S.R.L.',$json${"period":"01/2023 — 12/2023","company":"LET’S CO S.R.L.","focus":{"it":"Supporto tecnico · utenti e connettività","en":"Technical support · users and connectivity"},"role":{"it":"Tecnico IT","en":"IT Technician"},"detail":{"it":"Supporto utenti, networking, VPN, Google Workspace, workstation e periferiche.","en":"User support, networking, VPN, Google Workspace, workstations and devices."}}$json$::jsonb,20,'published'),
  ('experience','mindset','MINDSET S.R.L.','MINDSET S.R.L.',$json${"period":"11/2021 — 02/2022","company":"MINDSET S.R.L.","focus":{"it":"Formazione sul campo · ecosistema SAP","en":"On-the-job training · SAP environment"},"role":{"it":"ABAP Developer · Stage SAP Developer","en":"ABAP Developer · SAP Developer Internship"},"detail":{"it":"Sviluppo ABAP, assistenza SAP, SAP Router e troubleshooting in ambiente ERP.","en":"ABAP development, SAP support, SAP Router and ERP troubleshooting."}}$json$::jsonb,30,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('infrastructure_case','identita-accessi','Gestione di utenti e permessi in dominio Windows','Managing users and permissions in a Windows domain',$json${"eyebrow":{"it":"Caso principale · Identità e accessi","en":"Main case · Identity and access"},"scenario":{"it":"Supporto quotidiano a utenti e risorse condivise in un ambiente aziendale basato su Windows Server e Active Directory.","en":"Day-to-day support for users and shared resources in a corporate Windows Server and Active Directory environment."},"problem":{"it":"Un accesso negato o una policy non applicata può dipendere dall’account, dai gruppi, dall’OU, dalla GPO o dai servizi di risoluzione del dominio.","en":"Denied access or a policy that does not apply may depend on the account, groups, OU, GPO or domain name-resolution services."},"analysis":{"it":"Verifico identità, appartenenze, ambito della policy, DNS e autenticazione prima di modificare la configurazione.","en":"I check identity, memberships, policy scope, DNS and authentication before changing configuration."},"intervention":{"it":"Gestisco utenti, gruppi, OU, permessi e GPO e intervengo sui servizi collegati quando necessario.","en":"I manage users, groups, OUs, permissions and GPOs and address related services when needed."},"verification":{"it":"Verifico nuovamente accesso, applicazione della policy e disponibilità della risorsa.","en":"I recheck access, policy application and resource availability."},"technologies":["Windows Server","Active Directory","GPO","DNS","DHCP"],"result":{"it":"L’utente torna a lavorare con i soli permessi necessari.","en":"The user can work again with only the required permissions."},"competencies":[{"it":"Gestione delle identità","en":"Identity management"},{"it":"Troubleshooting controllato","en":"Controlled troubleshooting"}],"diagram":[{"it":"Utente","en":"User"},"Active Directory",{"it":"Permessi","en":"Permissions"},{"it":"Risorsa autorizzata","en":"Authorised resource"}]}$json$::jsonb,10,'published'),
  ('infrastructure_case','connettivita','Diagnosi di connettività tra client e servizio aziendale','Diagnosing connectivity between a client and a business service',$json${"eyebrow":{"it":"Networking e accesso remoto","en":"Networking and remote access"},"scenario":{"it":"Supporto a reti aziendali, reparti produttivi e collegamenti VPN.","en":"Support for corporate networks, production departments and VPN connections."},"problem":{"it":"Un client non raggiunge una risorsa oppure la connessione remota non consente di proseguire il lavoro.","en":"A client cannot reach a resource, or a remote connection prevents work from continuing."},"analysis":{"it":"Verifico configurazione IP, percorso di rete, segmentazione, VPN e raggiungibilità del servizio.","en":"I check IP configuration, network path, segmentation, VPN and service reachability."},"intervention":{"it":"Correggo la configurazione coinvolta o circoscrivo il punto di guasto.","en":"I correct the affected configuration or isolate the fault domain."},"verification":{"it":"Ripeto i test di raggiungibilità e controllo l’accesso al servizio.","en":"I repeat reachability tests and confirm service access."},"technologies":["LAN","VLAN","VPN","Routing","Switching"],"result":{"it":"La causa viene isolata e l’accesso ripristinato o affidato al livello competente con contesto utile.","en":"The cause is isolated and access is restored or handed over with useful context."},"competencies":[{"it":"Troubleshooting per livelli","en":"Layered troubleshooting"}]}$json$::jsonb,20,'published'),
  ('infrastructure_case','supporto-sap','Supporto tecnico su accessi e componenti SAP','Technical support for SAP access and components',$json${"eyebrow":{"it":"Supporto applicativo","en":"Application support"},"scenario":{"it":"Assistenza agli utenti SAP in ambienti ERP.","en":"Support for SAP users in ERP environments."},"problem":{"it":"L’utente incontra un problema di accesso, configurazione del client o utilizzo dell’applicazione.","en":"A user encounters an access, client configuration or application issue."},"analysis":{"it":"Distinguo il problema locale da quello applicativo e verifico utente, client e collegamento.","en":"I distinguish local from application issues and check user, client and connection."},"intervention":{"it":"Intervengo su SAP GUI, gestione utenti, SAP Router e troubleshooting.","en":"I work on SAP GUI, user management, SAP Router and troubleshooting."},"verification":{"it":"Confermo con l’utente il nuovo accesso o preparo un’escalation circostanziata.","en":"I confirm access with the user or prepare a well-scoped escalation."},"technologies":["SAP GUI","SAP Router","ABAP"],"result":{"it":"Il problema viene risolto nel perimetro del supporto oppure inoltrato conservando il contesto.","en":"The issue is resolved within support scope or escalated with its context."},"competencies":[{"it":"Supporto agli utenti","en":"User support"}]}$json$::jsonb,30,'published'),
  ('infrastructure_case','operations','Manutenzione dell’infrastruttura in ambiente produttivo','Infrastructure maintenance in a production environment',$json${"eyebrow":"Operations","scenario":{"it":"Gestione operativa di server, ambienti virtualizzati, utenti e servizi collegati alla produzione.","en":"Operational management of servers, virtual environments, users and production-related services."},"problem":{"it":"Aggiornamenti, backup e anomalie devono essere gestiti senza introdurre modifiche non controllate.","en":"Updates, backups and incidents must be handled without uncontrolled changes."},"analysis":{"it":"Valuto servizio, dipendenze e rischio operativo.","en":"I assess the service, dependencies and operational risk."},"intervention":{"it":"Eseguo attività su Windows Server, VMware, backup e aggiornamenti con una sequenza verificabile.","en":"I work on Windows Server, VMware, backups and updates using a verifiable sequence."},"verification":{"it":"Controllo disponibilità del servizio ed esito dell’attività.","en":"I check service availability and the activity outcome."},"technologies":["VMware","Windows Server","Backup","VPN"],"result":{"it":"Il servizio viene riconsegnato dopo una verifica tecnica.","en":"The service is handed back after technical verification."},"competencies":[{"it":"Continuità operativa","en":"Operational continuity"}]}$json$::jsonb,40,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('web_project','portfolio-gaetano-russo','Portfolio professionale di Gaetano Russo','Gaetano Russo’s professional portfolio',$json${"type":{"it":"Progetto personale","en":"Personal project"},"status":"Online","audience":{"it":"Recruiter IT e professionisti interessati a un sito web.","en":"IT recruiters and professionals interested in a website."},"need":{"it":"Presentare nello stesso sito il profilo infrastrutturale e i lavori web senza confondere i due interlocutori.","en":"Present infrastructure experience and web work on the same site without confusing the two audiences."},"decisions":{"it":"Architettura statica, dati separati dall’interfaccia e due percorsi consultabili senza ricaricare la pagina.","en":"Static architecture, data separated from the interface and two paths without page reloads."},"features":{"it":"Contenuti bilingue, tema chiaro/scuro, video adattivo, cookie, modali accessibili, CV con informativa e form EmailJS.","en":"Bilingual content, light/dark theme, adaptive video, cookies, accessible dialogs, privacy-gated CV and EmailJS form."},"problems":{"it":"Organizzare i contenuti esistenti, preservare i deep link e limitare il peso dei video Canva.","en":"Organising existing content, preserving deep links and limiting Canva video impact."},"stack":["HTML5","CSS3","JavaScript","EmailJS","GitHub Pages"],"result":{"it":"Il sito pubblicato comprende homepage, pagine legali, articoli e contenuti bilingue.","en":"The published website includes the homepage, legal pages, articles and bilingual content."},"proof":{"it":"La pagina che stai consultando è il progetto in esecuzione.","en":"The page you are viewing is the running project."},"links":[{"label":{"it":"Apri il sito","en":"Open website"},"href":"https://gaetanorussoits1994-coder.github.io/portfolio-gaetano-russo/"}]}$json$::jsonb,10,'published'),
  ('web_project','luca-magarotto-photography','Luca Magarotto Photography','Luca Magarotto Photography',$json${"type":{"it":"Progetto reale per studio fotografico","en":"Live project for a photography studio"},"status":{"it":"Online","en":"Live"},"audience":{"it":"Fotografo e visitatori interessati ai suoi lavori.","en":"Photographer and visitors interested in his work."},"need":{"it":"Realizzare una presenza online professionale che organizzasse portfolio, progetti Fine Art, articoli e richieste di contatto.","en":"Create a professional online presence for portfolios, Fine Art projects, journal articles and contact enquiries."},"decisions":{"it":"Ho realizzato un sito bilingue con percorsi fotografici distinti e un’area amministrativa riservata con recupero password.","en":"I built a bilingual website with distinct photography paths and a restricted administration area with password recovery."},"features":{"it":"Portfolio In Studio e On Location, Fine Art Prints, Journal, Contatti, selettore IT/EN e accesso amministrativo.","en":"In Studio and On Location portfolios, Fine Art Prints, Journal, Contact, IT/EN selector and admin access."},"problems":{"it":"Organizzare servizi, progetti e contenuti editoriali mantenendo separata l’area di gestione.","en":"Organising services, projects and editorial content while keeping management separate."},"stack":["Next.js","React","Vercel"],"result":{"it":"Il sito è online su dominio personalizzato e le sezioni pubbliche verificate sono accessibili.","en":"The site is live on a custom domain and its verified public sections are accessible."},"links":[{"label":{"it":"Visita il sito","en":"Visit the website"},"href":"https://lucamagarotto42photography.it/"}]}$json$::jsonb,20,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, category, data, sort_order, status) values
  ('technical_lab','active-directory','Active Directory','Active Directory','access',$json${"category":"access","area":{"it":"Active Directory e accessi","en":"Active Directory and access"},"title":"Active Directory","mode":{"it":"Gestito e verificato","en":"Managed and verified"},"detail":{"it":"Gestione di identità, gruppi, OU, permessi, GPO e autenticazione centralizzata.","en":"Management of identities, groups, OUs, permissions, GPOs and centralised authentication."},"evidence":{"it":"Controllo di appartenenze, policy e accesso finale alla risorsa.","en":"Checks of memberships, policies and final resource access."},"tags":["GPO","DNS","Users"]}$json$::jsonb,10,'published'),
  ('technical_lab','windows-server','Windows Server','Windows Server','windows',$json${"category":"windows","area":{"it":"Sistemi Windows","en":"Windows systems"},"title":"Windows Server","mode":{"it":"Configurato e mantenuto","en":"Configured and maintained"},"detail":{"it":"Servizi di dominio, file server, backup e manutenzione.","en":"Domain services, file servers, backups and maintenance."},"evidence":{"it":"Verifica della disponibilità del servizio e dell’esito dell’attività.","en":"Verification of service availability and activity outcome."},"tags":["Server","Backup","Domain"]}$json$::jsonb,20,'published'),
  ('technical_lab','virtualizzazione','Virtualizzazione','Virtualisation','windows',$json${"category":"windows","area":{"it":"Ambienti di test","en":"Test environments"},"title":{"it":"Virtualizzazione","en":"Virtualisation"},"mode":{"it":"Configurato in ambienti virtuali","en":"Configured in virtual environments"},"detail":{"it":"Macchine virtuali, snapshot, reti virtuali e scenari di laboratorio.","en":"Virtual machines, snapshots, virtual networks and lab scenarios."},"evidence":{"it":"Uso di snapshot e ambienti isolati per attività ripetibili.","en":"Use of snapshots and isolated environments for repeatable activities."},"tags":["VMware","Snapshot","Lab"]}$json$::jsonb,30,'published'),
  ('technical_lab','sap-support','SAP Support','SAP Support','sap',$json${"category":"sap","area":{"it":"SAP e applicativi aziendali","en":"SAP and business applications"},"title":"SAP Support","mode":{"it":"Supportato e verificato con l’utente","en":"Supported and verified with the user"},"detail":{"it":"Supporto utenti, SAP GUI, SAP Router e troubleshooting.","en":"User support, SAP GUI, SAP Router and troubleshooting."},"evidence":{"it":"Distinzione tra problema locale e applicativo, conferma o escalation.","en":"Distinction between local and application issues, confirmation or escalation."},"tags":["SAP GUI","Router","ABAP"]}$json$::jsonb,40,'published'),
  ('technical_lab','enterprise-networking','Enterprise Networking','Enterprise Networking','network',$json${"category":"network","area":{"it":"Networking e troubleshooting","en":"Networking and troubleshooting"},"title":"Enterprise Networking","mode":{"it":"Analizzato per livelli","en":"Analysed layer by layer"},"detail":{"it":"Routing, switching, VLAN, VPN, subnetting e Wi-Fi survey.","en":"Routing, switching, VLANs, VPNs, subnetting and Wi-Fi surveys."},"evidence":{"it":"Controllo IP, percorso, segmentazione e raggiungibilità.","en":"Checks of IP, path, segmentation and reachability."},"tags":["LAN","VLAN","VPN"]}$json$::jsonb,50,'published'),
  ('technical_lab','docker','Docker','Docker','web',$json${"category":"web","area":{"it":"Sviluppo e ambienti","en":"Development and environments"},"title":"Docker","mode":{"it":"Studiato in laboratorio","en":"Studied in a lab"},"detail":{"it":"Immagini, container, Compose e ambienti riproducibili.","en":"Images, containers, Compose and reproducible environments."},"evidence":{"it":"Argomento di laboratorio, non presentato come progetto pubblicato.","en":"Lab topic, not presented as a published project."},"tags":["Docker","Compose","Containers"]}$json$::jsonb,60,'published'),
  ('technical_lab','nextjs','Next.js','Next.js','web',$json${"category":"web","area":{"it":"Sviluppo web","en":"Web development"},"title":"Next.js","mode":{"it":"Studiato in laboratorio","en":"Studied in a lab"},"detail":{"it":"Routing, SEO, componenti e performance.","en":"Routing, SEO, components and performance."},"evidence":{"it":"Argomento di laboratorio; attribuito ai progetti soltanto quando verificato.","en":"Lab topic; attributed to projects only when verified."},"tags":["Routing","SEO","Performance"]}$json$::jsonb,70,'published'),
  ('technical_lab','supabase','Supabase','Supabase','web',$json${"category":"web","area":{"it":"Backend e dati","en":"Backend and data"},"title":"Supabase","mode":{"it":"Studiato in laboratorio","en":"Studied in a lab"},"detail":{"it":"PostgreSQL, Auth, API REST, realtime e Storage.","en":"PostgreSQL, Auth, REST APIs, realtime and Storage."},"evidence":{"it":"Integrazione predisposta nel portfolio e attiva solo dopo configurazione.","en":"Integration prepared in the portfolio and active only after configuration."},"tags":["PostgreSQL","Auth","REST API"]}$json$::jsonb,80,'published')
on conflict (content_type, slug) do nothing;

insert into public.content_items (content_type, slug, title_it, title_en, data, sort_order, status) values
  ('certificate','ifoa-abap','IFOA Academy Developer','IFOA Academy Developer',$json${"title":"IFOA Academy Developer","subtitle":{"it":"Programmatore ABAP · Attestato di frequenza","en":"ABAP Developer · Attendance certificate"},"detail":{"it":"Sviluppo ABAP, logiche SAP e formazione tecnica.","en":"ABAP development, SAP logic and technical training."},"image":"immagini/Attestato ABAP.png"}$json$::jsonb,10,'published'),
  ('certificate','telsy-awareness','TelsySkills','TelsySkills',$json${"title":"TelsySkills","subtitle":{"it":"CyberSecurity Awareness · Attestato di partecipazione","en":"Cybersecurity Awareness · Participation certificate"},"detail":{"it":"Consapevolezza cyber e protezione degli ambienti aziendali.","en":"Cyber awareness and protection of corporate environments."},"image":"immagini/Attestato Telsy.png"}$json$::jsonb,20,'published'),
  ('contact_link','email','Email','Email','{"kind":"email","url":"mailto:gaetano.russoits1994@gmail.com"}'::jsonb,10,'published'),
  ('contact_link','linkedin','LinkedIn','LinkedIn','{"kind":"linkedin","url":"https://www.linkedin.com/in/gaetano-russo-b11664220/"}'::jsonb,20,'published')
on conflict (content_type, slug) do nothing;
